### ISSUE TITLE
Создать таблицу космических аппаратов

### ISSUE THREAD

**Issue by ScareCrowZV** [KAOrlov/DB_UNIVERSE#3]
Создать таблицу/таблицы отражающую космические аппараты и заложить отражение необходимых характеристик, которые могут быть полезны при выполнении расчётов или аналитики в БД в случае если космическим аппаратам нужно исследовать звёздные системы. ( все характеристики должны являться опираться на реальные аппараты и исследования).

**Comment by KAOrlov** [comment]
Создал таблицу касмических апратов
